{
  "Header": {
    "Original": "CVE-2020-36277 (Leptonica before 1.80.0 allows a denial of service (application crash) ...)",
    "Line": 166986,
    "ID": "CVE-2020-36277",
    "Description": "(Leptonica before 1.80.0 allows a denial of service (application crash) ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2612-1}",
      "Line": 166987,
      "Type": "xref",
      "Bugs": [
        "DLA-2612-1"
      ]
    },
    {
      "Original": "- leptonlib 1.79.0-1.1 (bug #985089)",
      "Line": 166988,
      "Type": "package",
      "Package": "leptonlib",
      "Kind": "fixed",
      "Version": "1.79.0-1.1",
      "BugNo": 985089
    },
    {
      "Original": "[buster] - leptonlib 1.76.0-1+deb10u1",
      "Line": 166989,
      "Type": "package",
      "Release": "buster",
      "Package": "leptonlib",
      "Kind": "fixed",
      "Version": "1.76.0-1+deb10u1"
    },
    {
      "Original": "NOTE: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21997",
      "Line": 166990,
      "Type": "NOTE",
      "Description": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21997"
    },
    {
      "Original": "NOTE: https://github.com/DanBloomberg/leptonica/pull/499",
      "Line": 166991,
      "Type": "NOTE",
      "Description": "https://github.com/DanBloomberg/leptonica/pull/499"
    }
  ]
}