{
  "Header": {
    "Original": "CVE-2018-1000807 (Python Cryptographic Authority pyopenssl version prior to version 17.5 ...)",
    "Line": 331546,
    "ID": "CVE-2018-1000807",
    "Description": "(Python Cryptographic Authority pyopenssl version prior to version 17.5 ...)"
  },
  "Annotations": [
    {
      "Original": "- pyopenssl 17.5.0-1",
      "Line": 331547,
      "Type": "package",
      "Package": "pyopenssl",
      "Kind": "fixed",
      "Version": "17.5.0-1"
    },
    {
      "Original": "[stretch] - pyopenssl \u003cno-dsa\u003e (Minor issue)",
      "Line": 331548,
      "Type": "package",
      "Release": "stretch",
      "Package": "pyopenssl",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - pyopenssl \u003cno-dsa\u003e (Minor issue, but also requires at least cryptography 2.1.4 which exposes the X509_up_ref method)",
      "Line": 331549,
      "Type": "package",
      "Release": "jessie",
      "Package": "pyopenssl",
      "Kind": "no-dsa",
      "Description": "Minor issue, but also requires at least cryptography 2.1.4 which exposes the X509_up_ref method"
    },
    {
      "Original": "NOTE: https://github.com/pyca/pyopenssl/pull/723",
      "Line": 331550,
      "Type": "NOTE",
      "Description": "https://github.com/pyca/pyopenssl/pull/723"
    },
    {
      "Original": "NOTE: https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509",
      "Line": 331551,
      "Type": "NOTE",
      "Description": "https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509"
    }
  ]
}