{
  "Header": {
    "Original": "CVE-2017-8054 (The function PdfPagesTree::GetPageNodeFromArray in PdfPageTree.cpp:464 ...)",
    "Line": 406785,
    "ID": "CVE-2017-8054",
    "Description": "(The function PdfPagesTree::GetPageNodeFromArray in PdfPageTree.cpp:464 ...)"
  },
  "Annotations": [
    {
      "Original": "- libpodofo 0.9.5-9 (bug #860995)",
      "Line": 406786,
      "Type": "package",
      "Package": "libpodofo",
      "Kind": "fixed",
      "Version": "0.9.5-9",
      "BugNo": 860995
    },
    {
      "Original": "[stretch] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 406787,
      "Type": "package",
      "Release": "stretch",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 406788,
      "Type": "package",
      "Release": "jessie",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 406789,
      "Type": "package",
      "Release": "wheezy",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: The motivation for no-dsa in wheezy is that there are no known",
      "Line": 406790,
      "Type": "NOTE",
      "Description": "The motivation for no-dsa in wheezy is that there are no known"
    },
    {
      "Original": "NOTE: services that use this library (apart from desktop applications)",
      "Line": 406791,
      "Type": "NOTE",
      "Description": "services that use this library (apart from desktop applications)"
    },
    {
      "Original": "NOTE: and the worst case is a DoS.",
      "Line": 406792,
      "Type": "NOTE",
      "Description": "and the worst case is a DoS."
    },
    {
      "Original": "NOTE: http://qwertwwwe.github.io/2017/04/22/PoDoFo-0-9-5-allows-remote-attackers-to-cause-a-denial-of-service-infinit-loop/",
      "Line": 406793,
      "Type": "NOTE",
      "Description": "http://qwertwwwe.github.io/2017/04/22/PoDoFo-0-9-5-allows-remote-attackers-to-cause-a-denial-of-service-infinit-loop/"
    },
    {
      "Original": "NOTE: PoC: https://github.com/qwertwwwe/PoC/blob/master/podofo/PoC",
      "Line": 406794,
      "Type": "NOTE",
      "Description": "PoC: https://github.com/qwertwwwe/PoC/blob/master/podofo/PoC"
    },
    {
      "Original": "NOTE: upstream commit: https://sourceforge.net/p/podofo/code/1872",
      "Line": 406795,
      "Type": "NOTE",
      "Description": "upstream commit: https://sourceforge.net/p/podofo/code/1872"
    },
    {
      "Original": "NOTE: partially reverted in: https://sourceforge.net/p/podofo/code/1881",
      "Line": 406796,
      "Type": "NOTE",
      "Description": "partially reverted in: https://sourceforge.net/p/podofo/code/1881"
    },
    {
      "Original": "NOTE: ... and re-fixed in: https://sourceforge.net/p/podofo/code/1882",
      "Line": 406797,
      "Type": "NOTE",
      "Description": "... and re-fixed in: https://sourceforge.net/p/podofo/code/1882"
    },
    {
      "Original": "NOTE: and https://sourceforge.net/p/podofo/code/1883",
      "Line": 406798,
      "Type": "NOTE",
      "Description": "and https://sourceforge.net/p/podofo/code/1883"
    }
  ]
}