{
  "Header": {
    "Original": "CVE-2019-7164 (SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injecti ...)",
    "Line": 304769,
    "ID": "CVE-2019-7164",
    "Description": "(SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injecti ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2811-1 DLA-1718-1}",
      "Line": 304770,
      "Type": "xref",
      "Bugs": [
        "DLA-2811-1",
        "DLA-1718-1"
      ]
    },
    {
      "Original": "[experimental] - sqlalchemy 1.3.0~b3+ds1-1",
      "Line": 304771,
      "Type": "package",
      "Release": "experimental",
      "Package": "sqlalchemy",
      "Kind": "fixed",
      "Version": "1.3.0~b3+ds1-1"
    },
    {
      "Original": "- sqlalchemy 1.2.18+ds1-2 (bug #922669)",
      "Line": 304772,
      "Type": "package",
      "Package": "sqlalchemy",
      "Kind": "fixed",
      "Version": "1.2.18+ds1-2",
      "BugNo": 922669
    },
    {
      "Original": "NOTE: https://github.com/sqlalchemy/sqlalchemy/issues/4481",
      "Line": 304773,
      "Type": "NOTE",
      "Description": "https://github.com/sqlalchemy/sqlalchemy/issues/4481"
    },
    {
      "Original": "NOTE: https://github.com/sqlalchemy/sqlalchemy/commit/30307c4616ad67c01ddae2e1e8e34fabf6028414",
      "Line": 304774,
      "Type": "NOTE",
      "Description": "https://github.com/sqlalchemy/sqlalchemy/commit/30307c4616ad67c01ddae2e1e8e34fabf6028414"
    }
  ]
}