{
  "Header": {
    "Original": "CVE-2021-46142 (An issue was discovered in uriparser before 0.9.6. It performs invalid ...)",
    "Line": 112093,
    "ID": "CVE-2021-46142",
    "Description": "(An issue was discovered in uriparser before 0.9.6. It performs invalid ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5063-1 DLA-2883-1}",
      "Line": 112094,
      "Type": "xref",
      "Bugs": [
        "DSA-5063-1",
        "DLA-2883-1"
      ]
    },
    {
      "Original": "- uriparser 0.9.6+dfsg-1",
      "Line": 112095,
      "Type": "package",
      "Package": "uriparser",
      "Kind": "fixed",
      "Version": "0.9.6+dfsg-1"
    },
    {
      "Original": "NOTE: https://github.com/uriparser/uriparser/issues/122",
      "Line": 112096,
      "Type": "NOTE",
      "Description": "https://github.com/uriparser/uriparser/issues/122"
    },
    {
      "Original": "NOTE: https://github.com/uriparser/uriparser/commit/c0483990e6b5b454f7c8752b36760cfcb0d093f5 (uriparser-0.9.6)",
      "Line": 112097,
      "Type": "NOTE",
      "Description": "https://github.com/uriparser/uriparser/commit/c0483990e6b5b454f7c8752b36760cfcb0d093f5 (uriparser-0.9.6)"
    },
    {
      "Original": "NOTE: https://github.com/uriparser/uriparser/pull/124",
      "Line": 112098,
      "Type": "NOTE",
      "Description": "https://github.com/uriparser/uriparser/pull/124"
    }
  ]
}