{
  "Header": {
    "Original": "CVE-2019-18874 (psutil (aka python-psutil) through 5.6.5 can have a double free. This  ...)",
    "Line": 268665,
    "ID": "CVE-2019-18874",
    "Description": "(psutil (aka python-psutil) through 5.6.5 can have a double free. This  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1998-1}",
      "Line": 268666,
      "Type": "xref",
      "Bugs": [
        "DLA-1998-1"
      ]
    },
    {
      "Original": "- python-psutil 5.6.7-1 (low; bug #944605)",
      "Line": 268667,
      "Type": "package",
      "Package": "python-psutil",
      "Kind": "fixed",
      "Version": "5.6.7-1",
      "Severity": "low",
      "BugNo": 944605
    },
    {
      "Original": "[buster] - python-psutil \u003cno-dsa\u003e (Minor issue)",
      "Line": 268668,
      "Type": "package",
      "Release": "buster",
      "Package": "python-psutil",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - python-psutil \u003cno-dsa\u003e (Minor issue)",
      "Line": 268669,
      "Type": "package",
      "Release": "stretch",
      "Package": "python-psutil",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/giampaolo/psutil/commit/7d512c8e4442a896d56505be3e78f1156f443465",
      "Line": 268670,
      "Type": "NOTE",
      "Description": "https://github.com/giampaolo/psutil/commit/7d512c8e4442a896d56505be3e78f1156f443465"
    },
    {
      "Original": "NOTE: https://github.com/giampaolo/psutil/pull/1616",
      "Line": 268671,
      "Type": "NOTE",
      "Description": "https://github.com/giampaolo/psutil/pull/1616"
    }
  ]
}