{
  "Header": {
    "Original": "CVE-2018-1088 (A privilege escalation flaw was found in gluster 3.x snapshot schedule ...)",
    "Line": 378511,
    "ID": "CVE-2018-1088",
    "Description": "(A privilege escalation flaw was found in gluster 3.x snapshot schedule ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2806-1}",
      "Line": 378512,
      "Type": "xref",
      "Bugs": [
        "DLA-2806-1"
      ]
    },
    {
      "Original": "- glusterfs 4.0.2-1 (bug #896128)",
      "Line": 378513,
      "Type": "package",
      "Package": "glusterfs",
      "Kind": "fixed",
      "Version": "4.0.2-1",
      "BugNo": 896128
    },
    {
      "Original": "[jessie] - glusterfs \u003cnot-affected\u003e (vulnerable code not present)",
      "Line": 378514,
      "Type": "package",
      "Release": "jessie",
      "Package": "glusterfs",
      "Kind": "not-affected",
      "Description": "vulnerable code not present"
    },
    {
      "Original": "[wheezy] - glusterfs \u003cnot-affected\u003e (vulnerable code not present)",
      "Line": 378515,
      "Type": "package",
      "Release": "wheezy",
      "Package": "glusterfs",
      "Kind": "not-affected",
      "Description": "vulnerable code not present"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1558721",
      "Line": 378516,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1558721"
    },
    {
      "Original": "NOTE: https://review.gluster.org/#/c/19899/",
      "Line": 378517,
      "Type": "NOTE",
      "Description": "https://review.gluster.org/#/c/19899/"
    },
    {
      "Original": "NOTE: https://review.gluster.org/#/c/19898/",
      "Line": 378518,
      "Type": "NOTE",
      "Description": "https://review.gluster.org/#/c/19898/"
    },
    {
      "Original": "NOTE: When fixing the issue it's important to not apply the incomplete fix and open",
      "Line": 378519,
      "Type": "NOTE",
      "Description": "When fixing the issue it's important to not apply the incomplete fix and open"
    },
    {
      "Original": "NOTE: CVE-2018-1112 causing that auth.allow allows all clients to mount volumes.",
      "Line": 378520,
      "Type": "NOTE",
      "Description": "CVE-2018-1112 causing that auth.allow allows all clients to mount volumes."
    },
    {
      "Original": "NOTE: Cf. https://bugzilla.redhat.com/show_bug.cgi?id=1570891",
      "Line": 378521,
      "Type": "NOTE",
      "Description": "Cf. https://bugzilla.redhat.com/show_bug.cgi?id=1570891"
    },
    {
      "Original": "NOTE: Needs: https://review.gluster.org/#/c/19899/1..2",
      "Line": 378522,
      "Type": "NOTE",
      "Description": "Needs: https://review.gluster.org/#/c/19899/1..2"
    }
  ]
}