{
  "Header": {
    "Original": "CVE-2021-4041 (A flaw was found in ansible-runner. An improper escaping of the shell  ...)",
    "Line": 118974,
    "ID": "CVE-2021-4041",
    "Description": "(A flaw was found in ansible-runner. An improper escaping of the shell  ...)"
  },
  "Annotations": [
    {
      "Original": "- ansible-runner 2.1.1-1",
      "Line": 118975,
      "Type": "package",
      "Package": "ansible-runner",
      "Kind": "fixed",
      "Version": "2.1.1-1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2028074",
      "Line": 118976,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2028074"
    },
    {
      "Original": "NOTE: https://github.com/ansible/ansible-runner/commit/3533f265f4349a3f2a0283158cd01b59a6bbc7bd (2.1.0)",
      "Line": 118977,
      "Type": "NOTE",
      "Description": "https://github.com/ansible/ansible-runner/commit/3533f265f4349a3f2a0283158cd01b59a6bbc7bd (2.1.0)"
    }
  ]
}