{
  "Header": {
    "Original": "CVE-2020-25626 (A flaw was found in Django REST Framework versions before 3.12.0 and b ...)",
    "Line": 204609,
    "ID": "CVE-2020-25626",
    "Description": "(A flaw was found in Django REST Framework versions before 3.12.0 and b ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5186-1}",
      "Line": 204610,
      "Type": "xref",
      "Bugs": [
        "DSA-5186-1"
      ]
    },
    {
      "Original": "- djangorestframework 3.12.1-1 (bug #971554)",
      "Line": 204611,
      "Type": "package",
      "Package": "djangorestframework",
      "Kind": "fixed",
      "Version": "3.12.1-1",
      "BugNo": 971554
    },
    {
      "Original": "[stretch] - djangorestframework \u003cno-dsa\u003e (Minor issue)",
      "Line": 204612,
      "Type": "package",
      "Release": "stretch",
      "Package": "djangorestframework",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/encode/django-rest-framework/commit/ae649336b110afe21b9429f2554052f31a9dfaf9",
      "Line": 204613,
      "Type": "NOTE",
      "Description": "https://github.com/encode/django-rest-framework/commit/ae649336b110afe21b9429f2554052f31a9dfaf9"
    },
    {
      "Original": "NOTE: Fixed upstream in 3.12.0 and 3.11.2",
      "Line": 204614,
      "Type": "NOTE",
      "Description": "Fixed upstream in 3.12.0 and 3.11.2"
    }
  ]
}