{
  "Header": {
    "Original": "CVE-2019-15522 (An issue was discovered in LINBIT csync2 through 2.0. csync_daemon_ses ...)",
    "Line": 281144,
    "ID": "CVE-2019-15522",
    "Description": "(An issue was discovered in LINBIT csync2 through 2.0. csync_daemon_ses ...)"
  },
  "Annotations": [
    {
      "Original": "- csync2 2.0-25-gc0faaf9-1 (bug #955445)",
      "Line": 281145,
      "Type": "package",
      "Package": "csync2",
      "Kind": "fixed",
      "Version": "2.0-25-gc0faaf9-1",
      "BugNo": 955445
    },
    {
      "Original": "[buster] - csync2 2.0-22-gce67c55-1+deb10u1",
      "Line": 281146,
      "Type": "package",
      "Release": "buster",
      "Package": "csync2",
      "Kind": "fixed",
      "Version": "2.0-22-gce67c55-1+deb10u1"
    },
    {
      "Original": "[stretch] - csync2 2.0-8-g175a01c-4+deb9u1",
      "Line": 281147,
      "Type": "package",
      "Release": "stretch",
      "Package": "csync2",
      "Kind": "fixed",
      "Version": "2.0-8-g175a01c-4+deb9u1"
    },
    {
      "Original": "[jessie] - csync2 \u003cno-dsa\u003e (Minor issue)",
      "Line": 281148,
      "Type": "package",
      "Release": "jessie",
      "Package": "csync2",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/LINBIT/csync2/pull/13/commits/0ecfc333da51575f188dd7cf6ac4974d13a800b1",
      "Line": 281149,
      "Type": "NOTE",
      "Description": "https://github.com/LINBIT/csync2/pull/13/commits/0ecfc333da51575f188dd7cf6ac4974d13a800b1"
    }
  ]
}