{
  "Header": {
    "Original": "CVE-2021-35042 (Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.orde ...)",
    "Line": 146770,
    "ID": "CVE-2021-35042",
    "Description": "(Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.orde ...)"
  },
  "Annotations": [
    {
      "Original": "- python-django \u003cnot-affected\u003e (Vulnerable code introduced in 3.1)",
      "Line": 146771,
      "Type": "package",
      "Package": "python-django",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced in 3.1"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2021/jul/01/security-releases/",
      "Line": 146772,
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2021/jul/01/security-releases/"
    },
    {
      "Original": "NOTE: Issue did affect only the experimental version and fixed in 2:3.2.5-1",
      "Line": 146773,
      "Type": "NOTE",
      "Description": "Issue did affect only the experimental version and fixed in 2:3.2.5-1"
    }
  ]
}