{
  "Header": {
    "Original": "CVE-2018-14678 (An issue was discovered in the Linux kernel through 4.17.11, as used i ...)",
    "Line": 339684,
    "ID": "CVE-2018-14678",
    "Description": "(An issue was discovered in the Linux kernel through 4.17.11, as used i ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4308-1 DLA-1531-1 DLA-1529-1}",
      "Line": 339685,
      "Type": "xref",
      "Bugs": [
        "DSA-4308-1",
        "DLA-1531-1",
        "DLA-1529-1"
      ]
    },
    {
      "Original": "- linux 4.17.14-1",
      "Line": 339686,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.17.14-1"
    },
    {
      "Original": "NOTE: https://xenbits.xen.org/xsa/advisory-274.html",
      "Line": 339687,
      "Type": "NOTE",
      "Description": "https://xenbits.xen.org/xsa/advisory-274.html"
    },
    {
      "Original": "NOTE: https://git.kernel.org/linus/b3681dd548d06deb2e1573890829dff4b15abf46",
      "Line": 339688,
      "Type": "NOTE",
      "Description": "https://git.kernel.org/linus/b3681dd548d06deb2e1573890829dff4b15abf46"
    }
  ]
}